services:
  frontend:
    image: ghcr.io/eosc-data-commons/matchmaker-frontend:latest
    build:
      context: .
      target: production
    ports:
      - "127.0.0.1:3000:3000"
      # - "127.0.0.1:5173:5173" # For development
    environment:
      - NODE_ENV=production
      - SEARCH_API_URL=http://search-api:8000
      - PLAYER_API_URL=https://dev1.player.eosc-data-commons.eu
